### ISSUE TITLE
LOC 3.4 Web API Service

### ISSUE THREAD

**Issue by imaitland** [ssec-jhu/evolver-ng#113]
HTTP Web API.
- [ ] enables remote configuration of the evolver.
  - [ ] vial configuration
  - [ ] attached hardware
  - [ ] calibration
  - [ ] experiment control
  - [ ] serial configuration
  - [ ] history configuration (no config now but it might)
- [ ] enables remote control of the evolver.
  - [ ] start experiment
  - [ ] stop experiment
  - [ ] abort experiment
  - [ ] sending control commands specific to installed hardware
    - [ ] e.g. speed of a stirer, or pump activity "Send an input like increase pump rate on vial 2"
      - [ ] Note: at present the experiment control is the established way of changing hardware behavior. Not strictly out of scope, but may affect priority.
- [ ] enables state visibility of the evolver
  - [ ] hardware sensor values over time dimension (historical and current).
    - [ ] for calibrated sensors only.
  - [ ] config state also (evolver meta state). 
  - [ ] Log dump feature. As a user I want to download data (historical and current) in a format convenient for offline analysis (e.g. CSV).
 
- [ ] Conforms to web standards for a HTTP Json data api.
