### ISSUE TITLE
LOC 3.5 Reference web user interface

### ISSUE THREAD

**Issue by imaitland** [ssec-jhu/evolver-ng#115]
- [ ]  A reference web user interface
  - [ ] a rich set of plots
  - [ ] feature complete, all the features of the HTTP API are used in the reference UI.
    - [ ] connect to local evolver-ng running instance
    - [ ] connect to evolver-ng running at arbitrary IP address
    - [ ] connect to evolver-ng running at any valid http address (URL). 
    - [ ] Update evolver config.
      - [ ] Update should be validated client side with failures reported to the user. 
      - [ ] Get schema for classinfo and use schema to validate classinfo changes.
    - [ ] Get hardware history
      - [ ] Plot history, for piece of hardware on each vial. User configurable y-axis on history.  
  - [ ] Prioritize features over design.
  - [ ] Production ready
    - [ ] unit tests, integration tests and e2e tests.
    - [ ] deployable to the evolver rpi device and runs there
    - [ ] deployable to local lab machine where it can connect to evolvers available over the network
    - [ ] source control
    - [ ] monitoring (?)
    - [ ] CI/CD
    - [ ] documentation 
  - [ ] contributions and modifications simple for a small team of maintain
