### ISSUE TITLE
LOC 3.2 Default Plugin Library

### ISSUE THREAD

**Issue by jamienoss** [ssec-jhu/evolver-ng#116]
While the core application provides the framework for a generic eVOLVER, specific functionality comes from the plugin modules. 
- [ ] We will develop plugins covering:
  - [ ] pre-packed hardware configuration including:
    - [ ] temperature control/sensing
    - [ ] LED control
    - [ ] photodiode sensing
    - [ ] pump control
    - [ ] stir rate control
  - [ ] experiment protocols:
    - [ ]  chemostat
    - [ ] turbidostat.
