### ISSUE TITLE
LOC 4.2 (EXTENSION) IoT cloud-based visibility and control

### ISSUE THREAD

**Issue by jamienoss** [ssec-jhu/evolver-ng#122]
There are inherent security risks with exposing the software’s HTTP API to publicly accessible networks, however, an IoT-like cloud data feed and pull-based control could be an additional offering.

- [ ] This would enable a single remote endpoint to monitor the status of any number of eVolvers from anywhere in the
world without the need for VPN.
- [ ] A cloud interface could support more rapid updates to user interface features, and provide a secure environment for remote control of eVolver experiments.
- [ ] Shipping experiment data to the cloud makes a natural archive.
- [ ] Finally, the same mechanism can collect anonymized data about eVolver usage (application telemetry) to gain insights for further improvements.
