### ISSUE TITLE
Complete architecture miro board

### ISSUE THREAD

**Issue by jamienoss** [ssec-jhu/evolver-ng#26]
[miro board](https://miro.com/app/board/uXjVKey1DnA=/)

List of core interfaces, sufficient enough to proceed with bulk implementation with low risk to later mass refactoring:
 - [x] ``evolver.base.BaseConfig``
 - [x]  ``evolver.base.ConfigDescriptor``
 - [x]  ``evolver.base.BaseInterface``
 - [x]  ``evolver.connection.interface.Connection``
 - [ ]  ``evolver.hardware.interface.Device`` (See #47)
 - [x]  ``evolver.controller.interface.Controller``
 - [x]  ``evolver.calibrator.interface.Calibrator``  (See #47)
 - [x]  ``evolver.histort.History``

Those that may require more fleshing out:
 - [ ]  ``evolver.controller.interface.Controller``
 - [ ]  ``evolver.histort.History`` (See #48)
